# Generated by Django 5.1.4 on 2025-04-07 22:48

from django.db import migrations

def update_site_info(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    Site.objects.filter(id=1).update(
        domain='blog-soul.com',
        name='Blog Soul'
    )

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_category'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.RunPython(update_site_info),
    ]
