# Generated by Django 5.1.4 on 2025-02-27 16:35

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_category_post_featured_image_alter_post_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
